apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    nodePort: 30006  # Tentukan port yang diinginkan di sini
  selector:
    app.kubernetes.io/name: argocd-server
