apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: juniorchen02/adoptpet:backend_2.3.1
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: mysecurepassword123
        - name: DB_NAME
          value: auth_db
        - name: DB_PORT
          value: "3306"
        resources:
          requests:
            memory: 1G
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort  # Mengubah tipe menjadi NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001  # Anda dapat menentukan port NodePort secara manual, atau biarkan kosong untuk memilih secara otomatis
  selector:
    app: backend