apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: juniorchen02/adoptpet:frontend_2.3.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 512Mi
            cpu: 400m
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # Mengubah tipe menjadi NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002  # Anda dapat menentukan port NodePort secara manual, atau biarkan kosong untuk memilih secara otomatis
  selector:
    app: frontend