apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-sa
  namespace: backend
secrets:
- name: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: backend
  name: github-actions-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "replicasets", "configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-role-binding
  namespace: backend
subjects:
- kind: ServiceAccount
  name: github-actions-sa
  namespace: backend
roleRef:
  kind: Role
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io
